let caps = [
    "Good day!",
    "Thanks for stopping by today.",
    "It's lovely to see you!",
    "This is split into readings and projects.",
    "Projects have three sections,",
    "each represents a segment of the web.",
    "What are you waiting for?",
    "Click around and explore!"
]

var d = new Date();
var hours = d.getHours();
if (hours < 12) {
    caps[0] = "Good morning!";
} else if (hours < 19) {
    caps[0] = "Good afternoon!"
}
else {
    caps[0] = "Good evening!";
}

let i = 0

function capRotate() {
    document.getElementById('caption-line').innerText = caps[i];
    if (i == caps.length - 1) {
        i = 0;
    } else {
        i++;
    }
}

setInterval(capRotate, 5000);

function clickProjects() {
    document.getElementById('readings').style.display = "none";
    document.getElementById('shady').style.display = "block";
}

function clickReadings() {
    document.getElementById('shady').style.display = "none";
    document.getElementById('readings').style.display = "block";
    
}

let readings = [
    "In the excerpt \"Mail Art and the Big Monster\", the author describes a phenomenon in which people create mailable art and describes its interaction with the Post system. The author explains the relationship between these two components, how the \"art\" aspect is fully within the artist's control but the \"mail\" aspect relinquishes this control and adheres to pre-established rules and processes. The \"Big Monster\", from my understanding, is the antagonist of mail art -- the rift in communication between people, which mail art thus combats. The big monster can be extrapolated to any policy or physical form that inhibits the travel of mail art, such as stamps or the Post office. Overall, I\'m not too sure what Mail Art is a response to, or what it hopes to accomplish.",
    "From the selections provided, the author was posed with the question, \"How do I make a website?\". The author provides a motivation for websites, encouraging everyone to create one such that it allows us to have full control over an aspect of ourselves online. Rather than subscribing to large social media platforms and expressing through there, personal websites give us power over the architecture, message, and content of our expression. Next, instead of discussing the traditional version of a website that may come to our minds today, the author proposes six metaphors to provide some ideas as to how a website can be implemented. From websites that have ever-changing content to those that change in sporadic bursts of work, these metaphorical archetypes challenge the reader to reframe their approach to creating websites. In the next excerpt, the author presents a method of media consumption that combats linear thinking. By reading multiple books at once or switching between two audio books, we can digest information from two unrelated fields and attempt to draw connections between the two, potentially revealing hidden connections or providing a supplementary perspective that aids in the understanding of both. I personally already prescribe to this method, but only because I never finish reading my books and enjoy switching around such that each time I re-open a book, I'm struck with the initial wave of novelty and excitement over and over again. As a CS student who has only ever seen personal websites in the context of a portfolio, it's interesting to consider how a personal website can be more than a showcase of works.",
    "A random thing that stood out to me -- what are underground e-book sites? Is it referring to libgen? The table depicting the analog and digital equivalents of actions is interesting, as it makes me wonder how the first person to create a digital reading experience decided to translate these actions, particularly the gestures. I took a Human Computer Interaction course and we often revisited how we connect to the internet -- through keyboard, mouse, and monitor -- and debated whether the current gestures and tools we use are truly the most intuitive. It's hard to imagine new gestures and interfaces, but particularly in the case of digital reading experiences, I'm excited to see what will change. The significance of zine culture's choice not to participate in large social media platforms for information sharing is interesting as well, since I've never thought of zines as counterculture. ",
    "In this essay exploring Geocities, I thought the old mechanisms of website building was very interesting. Before even discussing Geocities, I didn't know what CSS Zen Garden was so I looked it up; I didn't know anything like this existed before. When discussing how many people kept a small transparent image file to use as a spacer, it really emphasized just how different website building used to be. I also thought the mental exercise of comparing the destruction of Geocities to the potential destruction of user data on YouTube was interesting -- we definitely put so much faith into tech companies for maintaining our data storing it safely. Overall the analysis sharing cues of dead pages, characteristics of old websites such as borders, and investigation into the interconnectivity of old pages was interesting to imagine. It sounds like Geocities felt like a genuine neighborhood in a way that perhaps, most recently, Tumblr may have achieved, but no longer exists anywhere on the Internet. I cannot recall a single website or web community that offers the same degree of customizability, link surfing, or community.",
    "In this excerpt Price talks about how certain art (if it can be called art) relies upon distributed media to grant it context, status, and notoriety, in a way that galleries and curators do for paintings or sculptures. This new method of distribution raises the question of \"Is it art?\" and \"Is it public art?\" -- public art is long thought of as some sort of public intervention or space or statue that people make pilgrimages to and experience in person together. Price argues that digitally dispersed art is likewise public in its accessibility and cost, yet people engage with it alone in private -- but still at the same time. Furthermore, the people who create popular distributed pieces are often multi-faceted and not quite 'artists' but people who have multiple titles. These people are 'outsiders' to the art community, yet they are able to create pieces that have impact and influence. I thought the comment \"the artist of the future will be underground\" was quite interesting, and almost mimics the shift from huge record label artists to \"bedroom pop\" -- people, amateurs, outsiders begin to make reputable music too. I also thought the comment that \"collective experience is now based on simultaneous private experiences\" was fascinating as well. With social media and online streaming, people are able to connect and engage with works with no barrier to entry, no worry about being an experienced critic. I do not believe that we have an obligation to view the art firsthand. In an era where everything is commodified, including transportation, it feels discriminatory and pretentious to say that one must view the art firsthand. In order to adapt to changes in information distribution and technology, viewing art second hand should be just as valid. Especially if we were to discuss making art more accessible, second hand experiences are able to offer context surrounding the art that one may not be able to find in a gallery or museum. One other point I thought was interesting is how, since many pieces of art (or not art) are available online, viewing them is at our own discretion. Thus, there is an attached ethical choice to simply viewing the content, and an attached nuance that viewing or not viewing the content will ruin it or propel it. Finally, the way the readymade has manifested itself into modern distributions of art, and new definitions of art is almost prophetic. ",
    "This piece of text introduces and defines alt text as an image descriptor that is more brief than captions. It then describes how alt text is used to provide accessibility and context for those who may not be able to see the images themselves. Finally it introduces the concept of alt text as poetry, in that we should write alt text thoughtfully, leverage some creativity in what details to share, and have an experimental approach to writing these pieces of text. I thought it was interesting to hear about alt text from a more creative perspective, as I have only heard of it from a software/best-practices standpoint. I feel like there's little standardization or rules defining good alt text beyond simply describing the contents of the image, so this text provided some new approaches to frame my thinking.",
    "Duvall investigates how graphic designers adapted to postmodernism, and then suggests the next movement will be hypermodernism, where there becomes a \"standardization of the hyperlinked sign\". I'm not too sure what this means, even given the examples mentioned. The first case study examined is Mickey mouse, and how a cartoon was able to express social critiques (such as commentary on work and labor). This example leads into how there are people who practice critical design, where instead of operating through a client/designer relationship they design and deliver critical thoughts. It is mentioned that Disney could be considered the sole survivor of postmodernism, but I don't quite understand what that means -- what exactly did Disney survive? Overall, this section of the essay focuses on how Disney (or more specifically, Mickey) has been used to convey social and economic critiques, its meaning and symbolism surviving time and multiple different representations -- even something as basic as three circles. The critical designers leverage Disney as a critique on design and the market, how design has been merchandized, and homogenization (which I assume is directed towards the uniformity in style requested by corporations and industry designers).",
    "I first thought about this phenomenon in programming when I wondered what it was like to learn how to code in Asia. I thought, for some reason, that they'd have their own versions of Python or Java where the keywords were in Chinese or Korean. But then I thought about how annoying it was to type in these languages, whether it be searching for pinyin to yield the correct character or building characters phonetically -- then I looked it up and realized that it was all in English. It's funny how something so universal and imperative for a developing economy and society has been claimed by the Western world, simply because we arrived there first. Just because the first programming languages were written and introduced by an English speaker, the Western world quickly jumped on all the research and development and has created something so invaluable that others are forced to succumb and conform, rather than challenge and build something of their own. I remember my father considered learning how to program and perform a career switch, but never managed to follow through. I didn't understand why until I realized how difficult it was for him, a native Chinese speaker grappling with the English language, to further manipulate the English language and interpret it through small tokens of if's and while's. For a lot of people, English is hard enough to learn -- let alone reduce meaning and logic into such small pieces of language. I've built my own compiler once for a class here at Penn, and while I fully support the idea of new programming languages catered for different alphabets, I wonder if it's even possible to shift our perception of programming to adapt to new language structures. Even from locating memory locations and computer components, much of the nomenclature is rooted in English. We teach that the essence of programming is in bits and numbers, but how we abstract this low-level logic to something accessible will take a lot of research and thought. Ultimately, is all this research any easier than learning English?",
    "The reading selection describes two pieces of work, String Game and Body Missing, which rely upon technology and participant interaction. String Game specifically relied upon telecommunication technology which was still a prototype during this time, and participants had a few practice runs maneuvering based on Cat's Cradle. Their main performance slightly differed in that participants improvised and responded to each other. Body Missing came about years later as a website, and seems unrelated but explores the same concepts of participant improvisation and digital connection. I don't fully understand the meaning behind these works and what ties them together, or the significance despite String Game showing up in lecture a few times already, but I think it's interesting how the artist made it clear they were not interested in rehearsing the same thing over and over, but rather the realm of possible outcomes.",
    "Performing the Feed discusses the evolution of the post. Originally referring to nailing a piece of information to a wooden post for the town to see, we've evolved into a form of information distribution that is endless and anonymous, rightfully referred to as flow. Whereas print provided discrete pieces of information with sources that are easy to trace, digital posts provided the same discreteness but allowed for anonymity. These digital posts, while discrete, can be created and shared with such high turnover that it loses the distinct points in time that physical posts embodied. Now we've evolved into constant streams of information, whether it be livestreams or real-time chats with bots or humans. Information no longer has cited authors or defined boundaries, but rather exists just below the surface of reality -- every piece of information exists, yet in a way doesn't exist at all. It only comes to our attention if we ask for it. I find this observation of the evolution of information interesting, and I agree with Soulellis that it is vital we learn to dissect and identify critical characteristics of this new flow of information. Without proper time to digest content, it may be hard to think critically about information that is brought to us by algorithms. Especially as algorithms have different interpretations of semantics, coupled with the rise of bot-written content, I feel it is increasingly easier for us to mindlessly consume information without afterthought.",
    "I thought the storytelling was an interesting way to present algorithms as they are versus what they could be. Oftentimes with technology as ubiquitous as code and the internet, we easily forget alternative possibilities of how these systems could run and how they can be integrated into our lives. Many terms we throw around today that we consider technical jargon, such as the master/slave descriptor, stems from real social strife that brought harm to communities. I think the short story does a good job of inviting the reader to step back and consider their relationship with technology and their communities, and the role technology plays in distributing information -- biased or not.",
    "I think the jump from \"are humans robots\" to \"can creatives think\" made little sense to me. I'm currently taking an AI class and we discuss how there are multiple ways to engineer agents -- one of the choice being should they act rationally? Or should they act like humans? It's inherently assumed that people are irrational. My course also discussed the usage of CAPTCHA's in Googles own long term projects, such as recovering words from scanned books or confirming image training sets for machine learning. I think the introduction of this concept, where imitation and correlation are enough to speak something into reality, into art is a little bit more confusing for me and I'm curious what others think."
]

function reading(n) {
    document.getElementById('reading-text').innerText = readings[n];
    document.getElementById('reading-modal').style.display = "block";
}

function closeWindow() {
    document.getElementById('reading-modal').style.display = "none";
}

